export const PATH = {
  FEED: '/feed',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  NEW_PASSWORD: '/create-new-password',
  FORGOTPASSWORD: '/forgotpassword',
  REGISTRCONFIRMATION: '/registration-confirmation',
  POSTS: '/posts',
  PAYMENTS: '/payments',
  STATISTICS: '/statistics',
  USERS: '/users',
  FAVORITES: '/favorites',
  SETTINGS: '/settings',
  SEARCH: '/search',
  MESSENGER: '/messenger',
  MYPROFILE: '/profile',
  CREATE: '/create',
  LINK_EXPIRED: '/linkexpired',
  PUBLIC: '/',
  PRIVACY_POLICY: '/privacypolicies',
  TERMS_OF_SERVICE: '/termsofservice',
}
